### ISSUE TITLE
Feature request: Remove/replace not ASCII charaters

### ISSUE THREAD

**Issue by vromero** [apinanaivot/IKEA-3D-Model-Download-Button#1]
Thanks for the script, works beautifully

In the workflow to import in sketchup I have issues with non ASCII characters. This is entirely not the fault of the script, but perhaps it is a good feature to allow replacement of non ASCII characters?

Ideally the importer of sketchup should be fixed of course.

**Comment by apinanaivot** [comment]
You can edit this part of the code to add any characters you have issues with: 

// Remove invalid characters from filename
                    const cleanName = (name + ' - ' + color).replace(/[<>:"/\\|?*]/g, '');
